# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, null=True)),
                ('meaning', models.TextField(null=True)),
                ('examples', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Idiom',
                'verbose_name_plural': 'Idioms',
            },
        ),
    ]
