# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idioms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdiomOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('idiom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idioms.Idiom')),
            ],
            options={
                'verbose_name': 'Idiom of the Day',
                'verbose_name_plural': 'Idiom of the Day',
            },
        ),
    ]
